# Generated by Django 5.2.17 on 2026-10-02 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('jersey_number', models.PositiveSmallIntegerField()),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('DF', 'Defender'), ('MF', 'Midfielder'), ('FW', 'Forward')], max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='players', to='tournament.team')),
            ],
            options={
                'ordering': ['team__name', 'jersey_number'],
            },
        ),
        migrations.AddField(
            model_name='matchevent',
            name='player',
            field=models.ForeignKey(blank=True, help_text='Optional registered player associated with this event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_events', to='tournament.player'),
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(fields=('team', 'jersey_number'), name='unique_player_jersey_per_team'),
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.CheckConstraint(condition=models.Q(('jersey_number__gte', 1), ('jersey_number__lte', 99)), name='valid_player_jersey_number'),
        ),
    ]
