# Generated by Django 5.2.17 on 2026-10-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_player_matchevent_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='extra_time_minutes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='total_paused_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
