# Generated by Django 5.2.17 on 2026-10-04 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_match_extra_time_minutes_match_is_paused_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchevent',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='match_events', to='tournament.team'),
        ),
    ]
