# Generated by Django 5.2.17 on 2026-10-04 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_alter_matchevent_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='first_half_elapsed_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='first_half_ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='first_half_stoppage_minutes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='phase',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('first_half', 'First Half'), ('half_time', 'Half Time'), ('second_half', 'Second Half'), ('regulation_ended', 'Regulation Ended'), ('full_time', 'Full Time')], default='not_started', max_length=25),
        ),
        migrations.AddField(
            model_name='match',
            name='second_half_pause_baseline_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='second_half_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='second_half_stoppage_minutes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='type',
            field=models.CharField(choices=[('goal', 'Goal'), ('yellow_card', 'Yellow Card'), ('red_card', 'Red Card'), ('penalty_kick', 'Penalty Kick'), ('reward', 'Reward'), ('match_started', 'Match Started'), ('match_paused', 'Match Paused'), ('match_resumed', 'Match Resumed'), ('extra_time', 'Extra Time'), ('match_finished', 'Match Finished')], max_length=20),
        ),
    ]
