# Generated by Django 5.2.17 on 2026-10-05 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_match_first_half_elapsed_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='extra_time_elapsed_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='extra_time_first_half_elapsed_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='extra_time_first_half_ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='extra_time_first_half_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='extra_time_pause_baseline_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='extra_time_second_half_pause_baseline_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='extra_time_second_half_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='is_knockout',
            field=models.BooleanField(default=False, help_text='Enable knockout extra time and penalty shootouts.'),
        ),
        migrations.AddField(
            model_name='match',
            name='regulation_elapsed_seconds',
            field=models.PositiveIntegerField(default=5400),
        ),
        migrations.AlterField(
            model_name='match',
            name='phase',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('first_half', 'First Half'), ('half_time', 'Half Time'), ('second_half', 'Second Half'), ('regulation_ended', 'Regulation Ended'), ('full_time', 'Full Time'), ('extra_time_first_half', 'Extra Time - First Half'), ('extra_time_interval', 'Extra Time Interval'), ('extra_time_second_half', 'Extra Time - Second Half'), ('penalty_shootout', 'Penalty Shootout')], default='not_started', max_length=25),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='type',
            field=models.CharField(choices=[('goal', 'Goal'), ('yellow_card', 'Yellow Card'), ('red_card', 'Red Card'), ('penalty_kick', 'Penalty Kick'), ('reward', 'Reward'), ('match_started', 'Match Started'), ('match_paused', 'Match Paused'), ('match_resumed', 'Match Resumed'), ('extra_time', 'Extra Time'), ('match_finished', 'Match Finished'), ('half_time', 'Half Time'), ('second_half_started', 'Second Half Started'), ('regulation_ended', 'Regulation Ended'), ('extra_time_started', 'Extra Time Started'), ('extra_time_half_time', 'Extra Time Half Time'), ('et_second_half_started', 'Extra Time Second Half Started'), ('extra_time_ended', 'Extra Time Ended'), ('shootout_started', 'Penalty Shootout Started'), ('shootout_finished', 'Penalty Shootout Finished')], max_length=30),
        ),
    ]
