# Generated by Django 5.2.17 on 2026-10-05 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_match_extra_time_elapsed_seconds_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PenaltyShootoutKick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(blank=True, default='', max_length=150)),
                ('kick_number', models.PositiveIntegerField()),
                ('scored', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shootout_kicks', to='tournament.match')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shootout_kicks', to='tournament.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shootout_kicks', to='tournament.team')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('match', 'team', 'kick_number'), name='unique_team_shootout_kick')],
            },
        ),
    ]
