# Generated by Django 5.2.17 on 2026-10-05 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_penaltyshootoutkick'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='round_type',
            field=models.CharField(choices=[('group', 'Group / League'), ('knockout', 'Knockout')], default='group', max_length=20),
        ),
    ]
