# Generated by Django 5.2.17 on 2026-10-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_round_round_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchevent',
            name='type',
            field=models.CharField(choices=[('goal', 'Goal'), ('foul', 'Foul'), ('yellow_card', 'Yellow Card'), ('red_card', 'Red Card'), ('penalty_kick', 'Penalty Kick'), ('reward', 'Reward'), ('match_started', 'Match Started'), ('match_paused', 'Match Paused'), ('match_resumed', 'Match Resumed'), ('extra_time', 'Extra Time'), ('match_finished', 'Match Finished'), ('half_time', 'Half Time'), ('second_half_started', 'Second Half Started'), ('regulation_ended', 'Regulation Ended'), ('extra_time_started', 'Extra Time Started'), ('extra_time_half_time', 'Extra Time Half Time'), ('et_second_half_started', 'Extra Time Second Half Started'), ('extra_time_ended', 'Extra Time Ended'), ('shootout_started', 'Penalty Shootout Started'), ('shootout_finished', 'Penalty Shootout Finished')], max_length=30),
        ),
    ]
